AVRDUDEPROGRAMMER=atmelice_pdi
AVRDUDEMCU=x16e5
AVRDUDEDEVICE=usb
MCU=atxmega16e5
F_CPU=32000000

HFILES = $(wildcard *.h)
CFILES = $(wildcard *.c)

CALL_ANALYSIS=1

AFWROOT = afw
include ${AFWROOT}/Makefile.in
